export default function Services() {
  return (
    <div className="justify-items-center p-10 min-h-[calc(100vh-8rem)] bg-sky-100 text-black">
        <h1 className="text-4xl font-bold mb-6">Our services</h1>
        <div className="text-lg">
           Nam sed nisl quam. Etiam sit amet ultricies quam, sit amet porta lorem. Nullam quis cursus mauris, eget scelerisque enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec at arcu ac risus lobortis sagittis nec eget libero. Ut ultricies mi at ante ullamcorper, at hendrerit nulla lobortis. Curabitur nec neque a ipsum varius condimentum. Sed eu augue eget eros bibendum hendrerit. Nunc sodales ipsum volutpat dolor hendrerit, quis faucibus est ultrices. Etiam varius, dolor eget bibendum mattis, purus ipsum elementum massa, ornare iaculis libero justo ut magna. Nulla facilisi. Nullam ullamcorper, odio nec sagittis commodo, sapien urna aliquet tortor, sed elemen<br /><br />

           Nulla id varius purus. Etiam et urna gravida, congue velit sit amet, pharetra elit. Fusce tellus purus, mollis nec interdum sed, fringilla commodo dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi sit amet auctor erat, sit amet placerat justo. Donec sollicitudin est eu quam blandit mollis. Vivamus accumsan a est vel hendrerit. In luctus, massa eget vehicula auctor, libero sem ullamcorper dui, at posuere lectus felis vitae lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque a est in enim mollis congue. Donec dictum lacinia nisl id aliquam. Vivamus ut interdum velit. Morbi faucibus cursus felis ut tincidunt. Curabitur sit amet quam iaculis, mattis arcu eu, maximus diam. Donec tempus vulputate metus auctor placerat.<br /><br />

           Quisque nec nunc tincidunt, eleifend leo ut, aliquet est. Donec elit nisi, ultrices eu dapibus id, rhoncus eget risus. Nunc a maximus orci. Maecenas condimentum lectus non nibh aliquet ultrices. Pellentesque feugiat ac nibh ac cursus. Maecenas ac quam vel ligula tempor consectetur in pulvinar felis. In ullamcorper sodales ornare. In laoreet diam eu libero vestibulum laoreet at nec neque. Nam feugiat finibus turpis, nec egestas elit bibendum sed.<br /><br />

           Aliquam tristique viverra leo, sit amet pulvinar nibh mattis at. Nulla elit ante, posuere eget scelerisque eget, rutrum in lorem. Integer consequat scelerisque dolor, ac iaculis urna vulputate mollis. Nulla facilisi. Sed mollis diam et libero elementum, vitae vestibulum ligula ullamcorper. Nullam venenatis, erat nec congue porta, ligula nisi scelerisque nunc, vel consectetur mauris ipsum suscipit est. Aenean tempus ullamcorper lacinia. Nulla congue nibh metus, vitae lobortis erat rutrum in. Praesent consectetur efficitur nulla ut consequat. Nulla congue, nulla non semper vulputate, odio elit vulputate magna, eu tempor lectus erat ac eros. Cras eget diam vel purus lobortis placerat id a lacus. Pellentesque placerat erat tristique ante aliquam sollicitudin. Proin tincidunt sit amet diam vitae auctor. Nullam eu tempus diam, vel elementum ex. Proin sit amet mauris mattis, auctor justo sed, semper nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;<br /><br />

           Mauris imperdiet tortor imperdiet sollicitudin efficitur. Nunc id ante sodales, mollis justo sed, tincidunt tortor. Suspendisse sollicitudin dapibus augue, at bibendum nisi. Nullam molestie, eros eu pellentesque tincidunt, elit eros finibus tellus, a lacinia neque sapien vel sem. Maecenas scelerisque ut arcu sollicitudin elementum. Praesent id enim eu velit dictum ornare. Sed libero erat, consequat vitae blandit nec, aliquet sit amet nibh. Morbi ut ipsum molestie, lobortis sem eget, cursus risus. Curabitur quis tincidunt nisl. Cras eu molestie velit. Aliquam pretium maximus velit vitae fringilla. Nunc sed tristique lacus. Sed consequat accumsan lorem quis blandit. Suspendisse fringilla luctus nisi eget condimentum.     
        </div>
      </div>
  )
}