export default function Pricing() {
  return (
    <div className="w-full justify-items-center p-10 min-h-[calc(100vh-8rem)] bg-teal-100 text-black">
        <h1 className="text-4xl font-bold mb-6">Predictable pricing</h1>
        <div className="text-lg">
           Suspendisse potenti. Ut ac ultricies nulla. Quisque bibendum elit lectus, sed condimentum turpis condimentum id. Ut iaculis nisl quam, eu egestas diam ullamcorper quis. Etiam tincidunt interdum dui, at rhoncus libero faucibus et. Nulla ut metus dapibus, euismod metus at, fermentum nibh. In eu ipsum sed felis interdum ultrices. Aenean at sodales elit, sit amet vulputate velit.<br /><br />

           Integer faucibus cursus odio, luctus egestas ante. Sed ante mi, convallis et mattis sed, tristique eu ligula. Nulla ultrices porttitor odio nec condimentum. Sed suscipit orci quis augue consequat, id finibus diam laoreet. Donec sit amet rhoncus sem. Sed ac mollis justo. Vivamus convallis in enim ut mollis. Nullam vehicula velit a tellus dapibus varius. Sed molestie posuere sem, at efficitur nisi convallis eget. Phasellus quis purus et arcu facilisis tincidunt et et ligula.<br /><br />

           Quisque felis risus, rhoncus elementum consectetur vel, volutpat eu quam. Sed pretium id ante ornare convallis. Maecenas ut elementum nulla, eget luctus libero. Nunc ultricies tristique ultrices. Sed molestie, metus quis convallis ultricies, felis enim semper enim, sed semper elit mi ut metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam enim tortor, malesuada non urna ac, volutpat efficitur nunc. Vivamus et placerat nunc. Suspendisse vehicula cursus nulla, sed sagittis nisi auctor quis. Nunc nisi orci, consectetur eget aliquet ut, pulvinar a elit. Suspendisse molestie neque vitae mi sollicitudin, imperdiet tincidunt elit auctor.<br /><br />

           Ut rhoncus efficitur turpis eu ultrices. Sed lobortis viverra tortor sit amet fermentum. Curabitur vel eros eget tortor viverra suscipit eget nec odio. Nulla sit amet risus at libero pulvinar lacinia. Integer risus lectus, imperdiet vitae lorem a, imperdiet euismod risus. Nam cursus ligula id hendrerit maximus. Vestibulum ac suscipit leo, quis ullamcorper lectus. Nam est arcu, pulvinar non ipsum quis, volutpat finibus ipsum. Quisque at pharetra tellus, sit amet elementum magna. Vivamus auctor imperdiet massa, vel porttitor justo imperdiet et. Fusce vitae vulputate nisi, nec convallis augue. Sed placerat nisi enim, vel efficitur ipsum tincidunt at.<br /><br />

           Mauris sed felis non orci commodo vestibulum. Phasellus non tellus eu ante hendrerit auctor sit amet quis mauris. Sed efficitur sed urna quis tempor. Donec scelerisque, dui at sodales blandit, mauris lacus malesuada felis, in ornare ligula enim ac diam. Donec finibus tortor a tortor venenatis, vel lobortis nunc blandit. Mauris non varius enim. Nam maximus libero quis laoreet bibendum. Sed dui risus, gravida eu faucibus sit amet, varius non lectus. Donec hendrerit vitae ex et mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris pellentesque nunc est, at mollis diam tincidunt in. Nam semper ipsum vitae suscipit pellentesque. Phasellus malesuada metus et diam imperdiet cursus. In eros turpis, ultrices sed accumsan nec, varius vehicula neque. Aliquam porttitor eros ac tortor elementum sodales. Maecenas congue purus sed ante placerat, et dictum lectus sodales. 
        </div>
      </div>
  )
}